CREATE TABLE category (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                          name VARCHAR(100) NOT NULL,
                          description VARCHAR(500),
                          active BOOLEAN NOT NULL DEFAULT TRUE,
                          created_at TIMESTAMP NOT NULL,
                          updated_at TIMESTAMP NOT NULL,

                          CONSTRAINT pk_category PRIMARY KEY (id),
                          CONSTRAINT uk_category_name UNIQUE (name)
);