CREATE TABLE product (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                         name VARCHAR(150) NOT NULL,

                         description VARCHAR(500),

                         price NUMERIC(10, 2) NOT NULL,

                         stock_quantity INTEGER NOT NULL DEFAULT 0,

                         active BOOLEAN NOT NULL DEFAULT TRUE,

                         category_id BIGINT NOT NULL,

                         created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

                         updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

                         CONSTRAINT fk_product_category
                             FOREIGN KEY (category_id)
                                 REFERENCES category(id)
);